import { createClient } from "npm:@supabase/supabase-js@2.57.4";
import { PDFDocument, StandardFonts, rgb } from "npm:pdf-lib@1.17.1";
import {
  AlignmentType, Document, Footer, HeadingLevel, Packer, PageBreak, PageNumber,
  Paragraph, Table, TableCell, TableRow, TextRun, WidthType
} from "npm:docx@9.5.1";

const cors={
  "Access-Control-Allow-Origin":"*",
  "Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods":"POST, OPTIONS"
};
const J=(d:any,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{...cors,"Content-Type":"application/json"}});

function admin(){
  const j=Deno.env.get("SUPABASE_SECRET_KEYS");
  const k=j?JSON.parse(j)?.default:Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
  if(!k) throw Error("Server secret unavailable");
  return createClient(Deno.env.get("SUPABASE_URL")??"",k,{auth:{persistSession:false,autoRefreshToken:false}});
}
const safe=(v:any)=>String(v??"").trim();
const slug=(v:any)=>safe(v).toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,80)||"document";
const titleCase=(v:any)=>safe(v).replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());
const nowIso=()=>new Date().toISOString();

type Section={heading:string, paragraphs?:string[], bullets?:string[], rows?:{label:string,value:string}[]};

function professionalNotice(){
  return "PROFESSIONAL REVIEW REQUIRED: This working document was generated by EeziComply. It should be reviewed by an appropriately qualified legal, company-secretarial, tax, accounting or governance professional, as relevant, before it is relied on, adopted, signed, implemented or filed.";
}

function buildReviewSections(reviewType:string, review:any):Section[]{
  const r=review?.review_json||{};
  const sections:Section[]=[
    {heading:"Executive Review",paragraphs:[r.executive_summary||"",r.overall_commentary||"",r.overall_recommendation||""]},
  ];
  if(reviewType==="moi" && review.review_mode==="short_form_suitability"){
    const p=r.standard_moi_profile||{};
    sections.push({
      heading:"Standard MOI Suitability Profile",
      rows:[
        {label:"Outcome",value:titleCase(r.suitability_outcome||"")},
        {label:"Detected form",value:p.detected_form||review.detected_form||""},
        {label:"What it means",value:p.what_it_means||""},
        {label:"Why it may be suitable",value:p.why_it_may_be_suitable||""}
      ]
    });
  }
  const findings=r.findings||r.conflicts||[];
  if(findings.length){
    sections.push({
      heading:reviewType==="alignment"?"Conflicts and Alignment Findings":"Material Findings",
      paragraphs:findings.map((f:any,i:number)=>{
        const head=f.title||f.topic||`Finding ${i+1}`;
        const parts=[
          `${i+1}. ${head}`,
          f.clause_reference? `Clause/reference: ${f.clause_reference}`:"",
          f.moi_reference? `MOI: ${f.moi_reference} - ${f.moi_position||""}`:"",
          f.sha_reference? `SHA: ${f.sha_reference} - ${f.sha_position||""}`:"",
          f.chatgpt_comment? `EeziComply comment: ${f.chatgpt_comment}`:"",
          f.why_it_matters? `Why it matters: ${f.why_it_matters}`:"",
          f.companies_act_position? `Companies Act position: ${f.companies_act_position}`:"",
          f.legal_position? `Legal position: ${f.legal_position}`:"",
          f.legal_precedence_position? `Precedence/legal position: ${f.legal_precedence_position}`:"",
          f.recommendation? `Recommendation: ${f.recommendation}`:"",
          f.recommended_resolution? `Recommended resolution: ${f.recommended_resolution}`:"",
          f.professional_review_recommendation? `Professional review: ${f.professional_review_recommendation}`:""
        ].filter(Boolean);
        return parts.join("\n");
      })
    });
  }
  const proposed=r.proposed_changes||[];
  if(proposed.length){
    sections.push({
      heading:"Recommended Changes",
      paragraphs:proposed.map((c:any,i:number)=>[
        `${i+1}. ${c.title||"Recommended change"}`,
        c.clause_reference?`Reference: ${c.clause_reference}`:"",
        c.current_position?`Current position: ${c.current_position}`:"",
        c.proposed_change?`Proposed change: ${c.proposed_change}`:"",
        c.reason?`Reason: ${c.reason}`:"",
        c.professional_review_recommendation?`Professional review: ${c.professional_review_recommendation}`:""
      ].filter(Boolean).join("\n"))
    });
  }
  const priorities=r.priority_actions||[];
  if(priorities.length) sections.push({heading:"Priority Actions",bullets:priorities.map((p:any)=>`${p.priority}. ${p.action} - ${p.reason}`)});
  if(r.trigger_events_for_future_review?.length) sections.push({heading:"Future Review Triggers",bullets:r.trigger_events_for_future_review});
  if(r.questions_for_company?.length) sections.push({heading:"Questions / Matters to Confirm",bullets:r.questions_for_company});
  if(r.questions_for_shareholders?.length) sections.push({heading:"Questions / Matters to Confirm",bullets:r.questions_for_shareholders});
  if(r.limitations?.length) sections.push({heading:"Limitations",bullets:r.limitations});
  sections.push({heading:"Professional Review",paragraphs:[professionalNotice()]});
  return sections;
}

function buildChecklistSections(review:any):Section[]{
  const steps=review?.next_steps_json||[];
  const sections:Section[]=[];
  sections.push({heading:"Implementation Checklist",paragraphs:["Use this checklist after the revised working draft has been prepared. Each step should be completed and evidenced before the governance change is treated as complete."]});
  for(let i=0;i<steps.length;i++){
    const s=steps[i]||{};
    sections.push({
      heading:`${i+1}. ${s.title||"Next step"}`,
      paragraphs:[
        s.explanation||"",
        s.responsible_person?`Responsible: ${s.responsible_person}`:"",
        s.completion_test?`Complete when: ${s.completion_test}`:"",
        s.professional_review_recommendation?`Professional review: ${s.professional_review_recommendation}`:""
      ].filter(Boolean),
      bullets:[...(s.actions||[]),...(s.evidence_to_keep||[]).map((x:string)=>`Evidence to keep: ${x}`)]
    });
  }
  sections.push({heading:"Professional Review",paragraphs:[professionalNotice()]});
  return sections;
}

function textDocumentSections(kind:string, review:any):Section[]{
  if(kind==="revised_moi") return [
    {heading:"Revised Memorandum of Incorporation - Working Draft",paragraphs:[review.revised_moi_text||""]},
    {heading:"Professional Review",paragraphs:[professionalNotice()]}
  ];
  if(kind==="revised_sha") return [
    {heading:"Revised Shareholders' Agreement - Working Draft",paragraphs:[review.revised_sha_text||""]},
    {heading:"Professional Review",paragraphs:[professionalNotice()]}
  ];
  return [];
}

function docxParagraphsFromText(text:string){
  const lines=safe(text).split(/\n+/).map(x=>x.trim()).filter(Boolean);
  return lines.map(line=>{
    const isMain=/^(ARTICLE|SCHEDULE|ANNEXURE|APPENDIX)\b/i.test(line)||/^[A-Z][A-Z\s&()/-]{5,}$/.test(line);
    const isClause=/^\d+(?:\.\d+)*[.)]?\s+/.test(line);
    const isSignature=/^(SIGNED|SIGNATURE|FOR AND ON BEHALF|WITNESS)\b/i.test(line);
    if(isMain) return new Paragraph({heading:HeadingLevel.HEADING_1,spacing:{before:240,after:100},children:[new TextRun({text:line,bold:true,font:"Arial",size:26,color:"102445"})]});
    if(isClause) return new Paragraph({spacing:{before:100,after:90,line:300},children:[new TextRun({text:line,font:"Arial",size:22,bold:/^\d+[.)]\s+/.test(line)})]});
    if(isSignature) return new Paragraph({spacing:{before:220,after:120},children:[new TextRun({text:line,font:"Arial",size:22,bold:true})]});
    return new Paragraph({spacing:{after:100,line:300},alignment:AlignmentType.JUSTIFIED,children:[new TextRun({text:line,font:"Arial",size:22})]});
  });
}

async function makeDocx(docTitle:string, company:string, version:number, sections:Section[]){
  const children:any[]=[
    new Paragraph({alignment:AlignmentType.CENTER,spacing:{after:120},children:[new TextRun({text:"EeziComply",bold:true,font:"Arial",size:34,color:"102445"})]}),
    new Paragraph({alignment:AlignmentType.CENTER,spacing:{after:120},children:[new TextRun({text:"Company Secretary in your pocket",italics:true,font:"Arial",size:20,color:"6B7280"})]}),
    new Paragraph({alignment:AlignmentType.CENTER,spacing:{before:400,after:220},children:[new TextRun({text:docTitle,bold:true,font:"Arial",size:32,color:"102445"})]}),
    new Paragraph({alignment:AlignmentType.CENTER,spacing:{after:100},children:[new TextRun({text:company||"Company not supplied",font:"Arial",size:24})]}),
    new Table({
      width:{size:100,type:WidthType.PERCENTAGE},
      rows:[
        new TableRow({children:[
          new TableCell({children:[new Paragraph({children:[new TextRun({text:"Document status",bold:true,font:"Arial",size:20})]})]}),
          new TableCell({children:[new Paragraph({children:[new TextRun({text:"Professional Review Required",font:"Arial",size:20})]})]})
        ]}),
        new TableRow({children:[
          new TableCell({children:[new Paragraph({children:[new TextRun({text:"Version",bold:true,font:"Arial",size:20})]})]}),
          new TableCell({children:[new Paragraph({children:[new TextRun({text:String(version),font:"Arial",size:20})]})]})
        ]}),
        new TableRow({children:[
          new TableCell({children:[new Paragraph({children:[new TextRun({text:"Generated",bold:true,font:"Arial",size:20})]})]}),
          new TableCell({children:[new Paragraph({children:[new TextRun({text:new Date().toLocaleDateString("en-ZA"),font:"Arial",size:20})]})]})
        ]})
      ]
    }),
    new Paragraph({spacing:{before:260,after:120},children:[new TextRun({text:professionalNotice(),bold:true,font:"Arial",size:20,color:"8A3D19"})]}),
    new Paragraph({children:[new PageBreak()]})
  ];

  for(const s of sections){
    children.push(new Paragraph({heading:HeadingLevel.HEADING_1,spacing:{before:260,after:120},children:[new TextRun({text:s.heading,bold:true,font:"Arial",size:28,color:"102445"})]}));
    for(const p of s.paragraphs||[]) children.push(...docxParagraphsFromText(p));
    if(s.rows?.length){
      children.push(new Table({
        width:{size:100,type:WidthType.PERCENTAGE},
        rows:s.rows.map(r=>new TableRow({children:[
          new TableCell({width:{size:30,type:WidthType.PERCENTAGE},children:[new Paragraph({children:[new TextRun({text:r.label,bold:true,font:"Arial",size:20})]})]}),
          new TableCell({width:{size:70,type:WidthType.PERCENTAGE},children:[new Paragraph({children:[new TextRun({text:r.value,font:"Arial",size:20})]})]})
        ]}))
      }));
    }
    for(const b of s.bullets||[]) children.push(new Paragraph({bullet:{level:0},spacing:{after:80,line:300},children:[new TextRun({text:b,font:"Arial",size:22})]}));
  }

  const doc=new Document({
    styles:{default:{document:{run:{font:"Arial",size:22},paragraph:{spacing:{line:300,after:100}}}}},
    sections:[{
      properties:{page:{margin:{top:900,right:900,bottom:900,left:900}}},
      children,
      footers:{default:new Footer({children:[new Paragraph({
        alignment:AlignmentType.CENTER,
        children:[new TextRun({text:"EeziComply | Professional Review Required | Page ",font:"Arial",size:18,color:"6B7280"}),new TextRun({children:[PageNumber.CURRENT],font:"Arial",size:18,color:"6B7280"})]
      })]})}
    }]
  });
  return new Uint8Array(await Packer.toBuffer(doc));
}

function wrap(s:string,max=88){
  const words=safe(s).split(/\s+/),out:string[]=[];let line="";
  for(const w of words){if((line+" "+w).trim().length>max){if(line)out.push(line);line=w}else line=(line+" "+w).trim()}
  if(line)out.push(line);return out.length?out:[""];
}
async function makePdf(docTitle:string, company:string, version:number, sections:Section[]){
  const pdf=await PDFDocument.create();
  const font=await pdf.embedFont(StandardFonts.Helvetica),bold=await pdf.embedFont(StandardFonts.HelveticaBold);
  let page=pdf.addPage([595.28,841.89]),y=790;
  const left=52,width=491;
  const newPage=()=>{page=pdf.addPage([595.28,841.89]);y=790};
  const ensure=(h=35)=>{if(y<h+55)newPage()};
  const line=(t:string,size=10,isBold=false,indent=0,color=rgb(.07,.13,.24))=>{
    for(const l of wrap(t,Math.max(28,Math.floor((width-indent)/(size*.52))))){
      ensure(size+8);page.drawText(l,{x:left+indent,y,size,font:isBold?bold:font,color});y-=size+5;
    }
  };
  const heading=(t:string,size=16)=>{ensure(size+18);line(t,size,true,0,rgb(.04,.13,.26));y-=5};
  heading("EeziComply",19);line("Company Secretary in your pocket",10,false,0,rgb(.4,.44,.52));y-=18;
  heading(docTitle,18);line(company||"Company not supplied",12,true);y-=10;
  line(`Document status: Professional Review Required   |   Version: ${version}   |   Generated: ${new Date().toLocaleDateString("en-ZA")}`,9,false,0,rgb(.35,.39,.46));y-=12;
  line(professionalNotice(),9,true,0,rgb(.54,.24,.10));y-=15;
  newPage();
  for(const s of sections){
    heading(s.heading,14);
    for(const p of s.paragraphs||[]){for(const para of safe(p).split(/\n+/)){line(para,10);y-=4}}
    for(const r of s.rows||[]){line(`${r.label}: ${r.value}`,10,true);y-=3}
    for(const b of s.bullets||[]){line("• "+b,10,false,10);y-=2}
    y-=8;
  }
  for(const [i,p] of pdf.getPages().entries()){
    p.drawText(`EeziComply | Professional Review Required | Page ${i+1} of ${pdf.getPageCount()}`,{x:left,y:24,size:8,font,color:rgb(.4,.44,.52)});
  }
  return new Uint8Array(await pdf.save());
}

Deno.serve(async(req)=>{
  if(req.method==="OPTIONS") return new Response("ok",{headers:cors});
  if(req.method!=="POST") return J({error:"Method not allowed"},405);
  try{
    const auth=req.headers.get("Authorization"); if(!auth) return J({error:"Authentication required"},401);
    const token=auth.replace(/^Bearer\s+/i,"");
    const a=admin();
    const {data:{user},error:ue}=await a.auth.getUser(token);
    if(ue||!user) return J({error:"Invalid session"},401);

    const body=await req.json();
    const reviewType=body?.review_type;
    const reviewId=body?.review_id;
    if(!["moi","sha","alignment"].includes(reviewType)||!reviewId) return J({error:"review_type and review_id are required"},400);

    const table=reviewType==="moi"?"eezicomply_moi_reviews":reviewType==="sha"?"eezicomply_sha_reviews":"eezicomply_alignment_reviews";
    const {data:review,error:re}=await a.from(table).select("*").eq("id",reviewId).single();
    if(re||!review) return J({error:"Review not found"},404);
    if(review.owner_id!==user.id) return J({error:"Forbidden"},403);

    const company=review.organisation_name||"Company";
    const available:{kind:string,title:string,sections:Section[]}[]=[
      {kind:"review_report",title:`${reviewType==="moi"?"MOI":reviewType==="sha"?"Shareholders' Agreement":"MOI ↔ Shareholders' Agreement Alignment"} Review Report`,sections:buildReviewSections(reviewType,review)}
    ];
    if((review.next_steps_json||[]).length) available.push({kind:"implementation_checklist",title:"Implementation Checklist",sections:buildChecklistSections(review)});
    if(review.revised_moi_text) available.push({kind:"revised_moi",title:"Revised Memorandum of Incorporation - Working Draft",sections:textDocumentSections("revised_moi",review)});
    if(review.revised_sha_text) available.push({kind:"revised_sha",title:"Revised Shareholders' Agreement - Working Draft",sections:textDocumentSections("revised_sha",review)});

    if(!available.length) return J({error:"No review output is available to generate yet."},409);

    const requested=Array.isArray(body?.document_kinds)&&body.document_kinds.length
      ?available.filter(x=>body.document_kinds.includes(x.kind))
      :available;
    const generated:any[]=[];

    for(const item of requested){
      const {data:prev}=await a.from("eezicomply_governance_outputs")
        .select("id,version,storage_path,file_format")
        .eq("owner_id",user.id).eq("review_type",reviewType).eq("review_id",reviewId).eq("document_kind",item.kind)
        .eq("is_current",true).order("version",{ascending:false});
      const version=(prev?.[0]?.version||0)+1;
      if(prev?.length){
        await a.from("eezicomply_governance_outputs").update({is_current:false,document_status:"superseded",updated_at:nowIso()})
          .eq("owner_id",user.id).eq("review_type",reviewType).eq("review_id",reviewId).eq("document_kind",item.kind).eq("is_current",true);
      }
      for(const fmt of ["docx","pdf"]){
        const bytes=fmt==="docx"?await makeDocx(item.title,company,version,item.sections):await makePdf(item.title,company,version,item.sections);
        const ext=fmt, mime=fmt==="docx"?"application/vnd.openxmlformats-officedocument.wordprocessingml.document":"application/pdf";
        const path=`${user.id}/${reviewType}/${reviewId}/${item.kind}/v${version}/${slug(company)}-${slug(item.kind)}-v${version}.${ext}`;
        const up=await a.storage.from("eezicomply-governance-outputs").upload(path,bytes,{contentType:mime,upsert:false});
        if(up.error) throw up.error;
        const display=`${company} - ${item.title} - v${version}.${ext}`;
        const {data:row,error:ie}=await a.from("eezicomply_governance_outputs").insert({
          owner_id:user.id,company_id:review.company_id||null,review_type:reviewType,review_id:reviewId,document_kind:item.kind,file_format:fmt,
          display_name:display,storage_path:path,mime_type:mime,version,is_current:true,
          document_status:"professional_review_required",professional_review_required:true,
          metadata:{company,title:item.title,generated_at:nowIso()}
        }).select("*").single();
        if(ie) throw ie;
        const {data:signed,error:se}=await a.storage.from("eezicomply-governance-outputs").createSignedUrl(path,3600);
        if(se) throw se;
        generated.push({...row,download_url:signed?.signedUrl});
      }
    }
    return J({ok:true,generated});
  }catch(e:any){
    return J({error:String(e?.message||e)},500);
  }
});